# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'

  pod 'ReachabilitySwift'
  pod 'NVActivityIndicatorView'
  pod 'Toaster'
  pod 'AlamofireObjectMapper'
end

target 'MartHoliday' do
	shared_pods
end

target 'MartHolidayTests' do
    # Pods for testing
#shared_pods
end

target 'MartHolidayTodayExtension' do
#    pod 'Firebase/Core'
#    pod 'Firebase/Database'
end
